app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('list.urls')),
    path('', include('message.urls')),
    path('', include('campaign.urls')),
    path('', include('image.urls')),
    path('', include('person.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/message/urls.py
from django.urls import path, re_path
from .views import create_message, view_messages, choose_fields, view_message, delete_message, choose_type, \
    create_html_message

urlpatterns = [
    path('choose_type/', choose_type, name="choose-type"),
    path('create_message/', create_message, name="create-message"),
    path('create_html_message/', create_html_message, name="create-html-message"),
    re_path(r'^choose_fields/(?P<messageid>\w+)/$', choose_fields, name="choose-fields"),
    re_path(r'^view_message/(?P<messageid>\w+)/$', view_message, name="view-message"),
    re_path(r'^delete_message/(?P<messageid>\w+)/$', delete_message, name="delete-message"),
    path('view_messages/', view_messages, name="view-messages"),
]

app/message/models.py
from django.db import models


class Message(models.Model):
    title = models.CharField(max_length=50, verbose_name='Title')
    diff_gender = models.BooleanField(null=True, verbose_name='Differentiable by gender')
    message = models.TextField(max_length=500, verbose_name='Message')
    message_female = models.TextField(max_length=500, null=True, blank=True, verbose_name='Message (F)')
    csv_fields = models.FileField(upload_to='uploads/message_fields', verbose_name='CSV File')
    html = models.BooleanField(default=False)

    def __str__(self):
        return self.title

app/message/forms.py
from django import forms
from .models import Message


class CreateMessageForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control"}))
    diff_gender = forms.BooleanField(initial=True, required=False,
                                     widget=forms.CheckboxInput(attrs={'class': "form-check"}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}), label="Message")
    message_female = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control'}), label="Message female")

    class Meta:
        model = Message
        fields = '__all__'
        exclude = ['html']


class ChooseFields(forms.Form):
    pass

app/message/views.py
import csv
import re

from django import forms
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Message

from .forms import CreateMessageForm, ChooseFields


@login_required()
def choose_type(request):
    return render(request, "choose_type.html", {})


@login_required
def create_message(request):
    form = CreateMessageForm(request.POST, request.FILES)
    if form.is_valid():
        initial_obj = form.save(commit=False)
        initial_obj.save()
        path = initial_obj.csv_fields.path
        field_dict = {}
        to_fill_fields = re.findall(r'{xx[0-9]+}', initial_obj.message)

        if initial_obj.diff_gender:
            for key in re.findall(r'{xx[0-9]+}', initial_obj.message_female):
                to_fill_fields.append(key)

        with open(path) as csv_file:
            csv_reader = csv.reader(csv_file, delimiter=',')
            keys = next(csv_reader)
            values = next(csv_reader)
            for key, value in zip(keys, values):
                field_dict[key] = value

        CHOICES = []
        for key in keys:
            CHOICES.append((key, key))

        id = str(initial_obj.id)
        request.session['FILL_FIELDS' + id] = to_fill_fields
        request.session['CHOICES' + id] = CHOICES
        request.session['FIELD_DICT' + id] = field_dict

        return HttpResponseRedirect(reverse('choose-fields', kwargs={'messageid': initial_obj.id}))

    context = {
        'form': form
    }

    return render(request, "create_message.html", context)


@login_required
def create_html_message(request):
    form = CreateMessageForm(request.POST, request.FILES)
    if 'submit_form' in request.POST:
        if form.is_valid():
            initial_obj = form.save(commit=False)
            initial_obj.html = True
            initial_obj.save()
            path = initial_obj.csv_fields.path
            field_dict = {}
            to_fill_fields = re.findall(r'{xx[0-9]+}', initial_obj.message)

            if initial_obj.diff_gender:
                for key in re.findall(r'{xx[0-9]+}', initial_obj.message_female):
                    to_fill_fields.append(key)
            with open(path) as csv_file:
                csv_reader = csv.reader(csv_file, delimiter=',')
                keys = next(csv_reader)
                values = next(csv_reader)
                for key, value in zip(keys, values):
                    field_dict[key] = value

            CHOICES = []
            for key in keys:
                CHOICES.append((key, key))

            id = str(initial_obj.id)
            request.session['FILL_FIELDS' + id] = to_fill_fields
            request.session['CHOICES' + id] = CHOICES
            request.session['FIELD_DICT' + id] = field_dict

            return HttpResponseRedirect(reverse('choose-fields', kwargs={'messageid': initial_obj.id}))

    elif 'preview_form' in request.POST:
        if form.is_valid():
            initial_obj = form.save(commit=False)
            content = initial_obj.message
            formatted_content = content.replace('cid:', '/media/uploads/images/')
            context = {
                'message': formatted_content
            }

            return render(request, "preview_html.html", context)

    context = {
        'form': form,
    }

    return render(request, "create_html_message.html", context)


@login_required
def choose_fields(request, messageid):
    if messageid:
        new_fields = {}
        FILL_FIELDS = request.session.get("FILL_FIELDS" + messageid)
        CHOICES = request.session.get("CHOICES" + messageid)
        FIELD_DICT = request.session.get("FIELD_DICT" + messageid)

        for field in FILL_FIELDS:
            new_fields[field] = forms.CharField(widget=forms.Select(choices=CHOICES))

        DynamicFieldForm = type('DynamicIngridientsForm',
                                (ChooseFields,),
                                new_fields)
        form = DynamicFieldForm(request.POST or None)

        if form.is_valid():
            try:
                message_obj = Message.objects.get(id=messageid)

                step = 1
                if message_obj.diff_gender:
                    step = 2

                for i in range(step):
                    print(i)
                    new_msg = message_obj.message if i == 0 else message_obj.message_female
                    for field in FILL_FIELDS:
                        new_msg = new_msg.replace(field, FIELD_DICT[form.cleaned_data[field]])
                    if i == 0:
                        message_obj.message = new_msg
                    else:
                        message_obj.message_female = new_msg
                    message_obj.save()

                request.session.modified = True
                del request.session["FILL_FIELDS" + messageid]
                del request.session["CHOICES" + messageid]
                del request.session["FIELD_DICT" + messageid]
                return HttpResponseRedirect(reverse('view-message', kwargs={'messageid': message_obj.id}))

            except Message.DoesNotExist:
                return render(request, "choose_fields.html", {'form': form})

        return render(request, "choose_fields.html", {'form': form})


@login_required
def view_messages(request):
    return render(request, "view_messages.html", {'messages': Message.objects.all()})


@login_required
def delete_message(request, messageid):
    Message.objects.filter(id=messageid).delete()
    return redirect(request.META['HTTP_REFERER'])


@login_required
def view_message(request, messageid):
    print(Message.objects.get(id=int(messageid)))
    return render(request, "view_message.html", {'message': Message.objects.get(id=messageid)})

app/message/templates/choose_fields.html
{% extends "base.html" %}

{% block extrastyle %}
<style>
    .create-list-form {
        width: 40%;
        padding: 25px 35px;
        border-radius: 10px;
        background-color: white;
    }
</style>
{% endblock %}

{% block content %}
<div style="display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100%;">
    <div class="d-flex flex-column create-list-form">
        <h3>Choose fields</h3>
        <form action="" method="post" enctype="multipart/form-data">
            <div id="list-form" class="d-flex flex-column">
                {% csrf_token %}
                {% for field in form %}
                <label>{{field.name}}</label>
                {{ field }}
                {% endfor %}
            </div>
            <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>

    </div>
</div>

<script>
    function submit() {
        const form = document.querySelector('form');
        const data = new URLSearchParams(new FormData(form).entries());
        console.log(data);
    }
</script>
{% endblock %}

app/message/templates/choose_type.html
{% extends "base.html" %}

{% block extrastyle %}
<style>
    .create-list-form {
        width: 40%;
        padding: 25px 35px;
        border-radius: 10px;
    }

    button {
        border: none;
        background: #878E88;
        color: #ffffff;
        width: 240px;
        height: 80px;
        font-size: 18px;
        border-radius: 4px;
        transition: 0.4s;
        overflow: hidden;
    }

    button:focus {
        outline: none;
    }

    button:before {
        content: '';
        display: block;
        position: absolute;
        background: rgba(255,255,255,.5);
        width: 60px;
        height: 100%;
        left: 0;
        top: 0;
        opacity: .5;
        filter: blur(30px);
    }

    button:after {
        content: '';
        display: block;
        position: absolute;
        background: rgba(255,255,255,.2);
        width: 30px;
        height: 100%;
        left: 30px;
        top: 0;
        opacity: 0;
        filter: blur(30px);
    }

    button:hover {
        background: #ffffff;
        color: #000000;
        cursor: pointer;
    }


</style>
{% endblock %}

{% block content %}
<div style="display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100%;">
    <div class="d-flex flex-column create-list-form">
        <div class="btn">
            <button onclick="window.location='/create_message';" type="button">TEXT</button>
            <button onclick="window.location='/create_html_message';" type="button">HTML</button>

        </div>
    </div>
</div>
{% endblock %}

app/message/templates/create_html_message.html
{% extends "base.html" %}

{% block extrastyle %}
<style>
    .create-list-form {
        width: 40%;
        padding: 25px 35px;
        border-radius: 10px;
        background-color: white;
    }
    #message_female {
        display: none;
    }
</style>
{% endblock %}

{% block content %}
<div style="display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100%;">
    <div class="d-flex flex-column create-list-form">
        <h3 style="text-align:center;">Create HTML Message</h3>
        <form action="" method="post" enctype="multipart/form-data">
            <div id="list-form" class="d-flex flex-column">
                {% csrf_token %}
                {% for field in form %}
                {% if field.name == 'diff_gender' %}
                <label>{{field.label}}</label>
                <input type="checkbox" name="diff_gender" onclick="onCheck();" id="id_diff_gender">
                {% else %}
                <div id="{{field.name}}">
                    <label>{{field.label}}</label>
                    {{ field }}
                </div>
                {% endif %}
                {% endfor %}
            </div>
            <div class="d-flex justify-content-center">
                <button type="submit" name="submit_form" value="submit" style="margin:5px;" class="btn btn-primary">Submit</button>
                <button type="submit" name="preview_form" value="submit" style="margin:5px;" class="btn btn-primary">Preview</button>
            </div>
        </form>

    </div>
</div>

<script>
    function onCheck() {
        let checkBox = document.getElementById("id_diff_gender");
        let message_female = document.getElementById("message_female");
        if (checkBox.checked === true) {
            message_female.style.display = "contents";
        } else {
            message_female.style.display = "none";
        }
    }
</script>

{% endblock %}

app/message/templates/create_message.html
{% extends "base.html" %}

{% block extrastyle %}
<style>
    .create-list-form {
        width: 40%;
        padding: 25px 35px;
        border-radius: 10px;
        background-color: white;
    }

    #message_female {
        display: none;
    }
</style>
{% endblock %}

{% block content %}
<div style="display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100%;">
    <div class="d-flex flex-column create-list-form">
        <h3 style="text-align:center;">Create TEXT Message</h3>
        <form action="" method="post" enctype="multipart/form-data">
            <div id="list-form" class="d-flex flex-column">
                {% csrf_token %}
                {% for field in form %}
                {% if field.name == 'diff_gender' %}
                <label>{{field.label}}</label>
                <input type="checkbox" name="diff_gender" onclick="onCheck();" id="id_diff_gender">
                {% else %}
                <div id="{{field.name}}">
                    <label>{{field.label}}</label>
                    {{ field }}
                </div>
                {% endif %}
                {% endfor %}
            </div>
            <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
</div>

<script>
    function onCheck() {
        let checkBox = document.getElementById("id_diff_gender");
        let message_female = document.getElementById("message_female");
        if (checkBox.checked === true) {
            message_female.style.display = "contents";
        } else {
            message_female.style.display = "none";
        }
    }
</script>

{% endblock %}

app/message/templates/preview_html.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title> Preview </title>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
    <style>
        .btn{
            font-family: "Roboto", sans-serif;
            font-size: 12px;
            color: white;
            background: #4287f5;
            border: none;
            position: static;
            margin-top: 20px;
            margin-left: 20px;
            width: 100px;
            padding: 15px;
            text-align: center;
            text-decoration: none;
            text-transform: uppercase;
            border-radius: 5px;
            cursor: pointer;
            transition: 0.3s;
        }
        .btn:hover, .btn:focus, .btn:active{
            background: #1c4dc9;
            color: white;
        }
    </style>
</head>
<body>
    <button class="btn" onclick="goBack()">Back</button>
    <hr>
    {{ message | safe }}
</body>
</html>

app/message/templates/view_message.html
{% extends "base.html" %}

{% block extrastyle %}
<style>
    .create-list-form {
        width: 40%;
        padding: 25px 35px;
        border-radius: 10px;
        background-color: white;
    }
</style>
{% endblock %}

{% block content %}
<div style="display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100%;">
    <!--    <div class="d-flex flex-column create-list-form">-->
    <!--        <h3>Message {{message.id}}</h3>-->
    <!--        <form action="" method="post" enctype="multipart/form-data">-->
    <!--            <div id="list-form" class="d-flex flex-column">-->
    <!--                <h5>Title: {{message.title}}</h5>-->
    <!--                <h5>Differentiate by gender: {{message.diff_gender}}</h5>-->
    <!--                <h5>Message: {{message.message}}</h5>-->
    <!--            </div>-->
    <!--        </form>-->
    <!--    </div>-->

    <div class="d-flex flex-column create-list-form">
        <h3>Message {{message.id}}</h3>

        <div id="list-form" class="d-flex flex-column">
            <label>Title</label>
            <input class="form-control" type="text" name="title" maxlength="50" required="" readonly id="id_title"
                   value="{{message.title}}">

            <label>diff_gender</label>
            {% if message.diff_gender %}
            <input type="checkbox" name="diff_gender" onclick="return false;" id="id_diff_gender" checked>
            <label>Message (F)</label>
            <textarea name="message" cols="40" rows="10" class="form-control" readonly required="" id="id_message"
            >{{message.message_female}}</textarea>
            {% else %}
            <input type="checkbox" name="diff_gender" onclick="return false;" id="id_diff_gender">
            {% endif %}
            <label>Message</label>
            <textarea name="message" cols="40" rows="10" class="form-control" readonly required="" id="id_message"
            >{{message.message}}</textarea>
        </div>


    </div>

</div>
{% endblock %}

app/message/templates/view_messages.html
{% extends "base.html" %}
{% load static %}
{% block extrastyle %}
<style>
    .box-header {
        display: flex;
        align-items: center;
    }

    .addBtn {
        font-size: 30px;
    }
</style>
    {% load filename %}
{% endblock %}
{% block content %}
<div style="padding: 10px; background-color: white" class="box">
    <div class="box-header">
        <h3 style="margin: 0">Messages</h3>
        <a class="addBtn" href="/choose_type">+</a>
    </div>
    <!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
            <tbody>
            <tr>
                <th>Title</th>
                <th>Differentiate by gender</th>
                <th>Fields file</th>
                <th>Delete</th>
            </tr>
            {% for message in messages %}
            <tr style="cursor: pointer" onclick="window.location='/view_message/{{message.id}}/';">
                <td>{{message.title}}</td>
                <td>{{message.diff_gender}}</td>
                <td>{{message.csv_fields|filename}}</td>
                <td><a href="/delete_message/{{message.id}}/"><img width="32px" src="{% static "icons/trash.svg" %}" alt="Trash"></a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- /.box-body -->
</div>
{% endblock %}